name: Hent FT 2015/2019 fra valg.dk og byg CSV

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 4 1 * *'   # (valgfrit) kør månedligt kl. 04:00 UTC

permissions:
  contents: write

jobs:
  fetch_build:
    runs-on: ubuntu-latest

    steps:
      - name: Tjek repo ud
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer lftp (SFTP klient)
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Debug: list SFTP-roden og gem som artifact
      - name: List alle top-mapper på SFTP (debug)
        run: |
          lftp -u "Valg","Valg" sftp://data.valg.dk -e "cls -1; bye" | tee sftp_root_dirs.txt

      - name: Upload SFTP root listing (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: sftp-root-listing
          path: sftp_root_dirs.txt

      # Robust søgning efter FT2019/FT2015 mapper + spejling
      - name: Spejl FT 2019 og 2015 rådata fra SFTP (robust søgning)
        run: |
          set -euo pipefail

          # Hvis du kender de præcise mappenavne, kan du hardcode dem her:
          # DIR2019="Folketingsvalg-847cec19-05ff-4eff-b433-f0e886b24b7d-2019-06-05"
          # DIR2015="Folketingsvalg-8b9462dd-2bb6-40f7-b160-2a625665124b-2015-06-18"

          # Ellers: find første match i roden (vi matcher begge rækkefølger)
          : "${DIR2019:=$( lftp -u "Valg","Valg" sftp://data.valg.dk -e "cls -1; bye" | \
            grep -Ei 'Folketingsvalg.*2019|2019.*Folketingsvalg' | head -n1 || true )}"
          : "${DIR2015:=$( lftp -u "Valg","Valg" sftp://data.valg.dk -e "cls -1; bye" | \
            grep -Ei 'Folketingsvalg.*2015|2015.*Folketingsvalg' | head -n1 || true )}"

          if [ -z "${DIR2019}" ]; then
            echo "❌ Kunne ikke finde FT2019-mappe. Her er hele SFTP-roden:"; cat sftp_root_dirs.txt || true; exit 1
          fi
          if [ -z "${DIR2015}" ]; then
            echo "❌ Kunne ikke finde FT2015-mappe. Her er hele SFTP-roden:"; cat sftp_root_dirs.txt || true; exit 1
          fi

          echo "✔️ Fundet FT2019 mappe: ${DIR2019}"
          echo "✔️ Fundet FT2015 mappe: ${DIR2015}"

          mkdir -p data/raw/ft/2019 data/raw/ft/2015

          echo "== Spejler 2019 =="
          lftp -u "Valg","Valg" sftp://data.valg.dk -e "
            set net:timeout 25; set net:max-retries 2; set sftp:auto-confirm yes;
            mirror -c --verbose \"${DIR2019}/Valgresultater\"         data/raw/ft/2019/Valgresultater;
            mirror -c --verbose \"${DIR2019}/Kandidatdata\"           data/raw/ft/2019/Kandidatdata || true;
            mirror -c --verbose \"${DIR2019}/Valggeografi\"           data/raw/ft/2019/Valggeografi;
            mirror -c --verbose \"${DIR2019}/Partistemmefordeling\"   data/raw/ft/2019/Partistemmefordeling || true;
            bye
          "

          echo "== Spejler 2015 =="
          lftp -u "Valg","Valg" sftp://data.valg.dk -e "
            set net:timeout 25; set net:max-retries 2; set sftp:auto-confirm yes;
            mirror -c --verbose \"${DIR2015}/Valgresultater\"         data/raw/ft/2015/Valgresultater;
            mirror -c --verbose \"${DIR2015}/Kandidatdata\"           data/raw/ft/2015/Kandidatdata || true;
            mirror -c --verbose \"${DIR2015}/Valggeografi\"           data/raw/ft/2015/Valggeografi;
            mirror -c --verbose \"${DIR2015}/Partistemmefordeling\"   data/raw/ft/2015/Partistemmefordeling || true;
            bye
          "

      - name: Vis rå filer (hurtigt overblik)
        run: |
          echo "== RAW 2019 ==" && find data/raw/ft/2019 -maxdepth 2 -type f | sort | head -n 40 || true
          echo "== RAW 2015 ==" && find data/raw/ft/2015 -maxdepth 2 -type f | sort | head -n 40 || true

      - name: Sæt op Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Byg CSV’er (JSON -> CSV i dit format)
        run: node scripts/build-ft-csv.mjs

      - name: Vis genererede CSV’er
        run: |
          echo "== CSV 2019 ==" && find data/ft/2019 -maxdepth 2 -type f -name "*.csv" | sort | head -n 40 || true
          echo "== CSV 2015 ==" && find data/ft/2015 -maxdepth 2 -type f -name "*.csv" | sort | head -n 40 || true

      - name: Commit & push ændringer
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(data): hent FT 2015/2019 fra valg.dk og byg CSV"
            git push
          else
            echo "Ingen ændringer at committe."
          fi
