name: Hent FT 2015/2019 fra valg.dk og byg CSV (robust)

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 4 1 * *'

permissions:
  contents: write

jobs:
  fetch_build:
    runs-on: ubuntu-latest

    steps:
      - name: Tjek repo ud
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer tools
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp netcat-openbsd

      - name: Definér år og mappenavne
        id: cfg
        run: |
          echo "DIR2015=Folketingsvalg-8b9462dd-2bb6-40f7-b160-2a625665124b-2015-06-18" >> $GITHUB_OUTPUT
          echo "DIR2019=Folketingsvalg-847cec19-05ff-4eff-b433-f0e886b24b7d-2019-06-05" >> $GITHUB_OUTPUT

      - name: Tjek om SFTP-port 22 er åben (hurtig test)
        id: sftpcheck
        continue-on-error: true
        run: |
          echo "Tester TCP 22 til data.valg.dk ..."
          nc -z -w 5 data.valg.dk 22 && echo "ok" || (echo "closed"; exit 1)

      - name: Afbryd pænt hvis SFTP er lukket
        if: steps.sftpcheck.outcome == 'failure'
        run: |
          echo "::warning ::SFTP på data.valg.dk svarer ikke (port 22 lukket). Prøv igen senere."
          echo "Springer download/byg over for denne kørsel."
          exit 0

      - name: Spejl FT 2019 (med retry/backoff)
        env:
          DIR: ${{ steps.cfg.outputs.DIR2019 }}
        run: |
          set -euo pipefail
          mkdir -p data/raw/ft/2019

          tries=0
          until [ $tries -ge 20 ]; do
            echo "== Spejler 2019 (forsøg $((tries+1))) =="
            if lftp -u "Valg","Valg" sftp://data.valg.dk -e "
              set net:timeout 20; set net:max-retries 1; set sftp:auto-confirm yes;
              mirror -c --verbose \"${DIR}/Valgresultater\" data/raw/ft/2019/Valgresultater;
              bye
            "; then
              echo "2019: OK"
              break
            else
              tries=$((tries+1))
              echo "2019: fejl – venter og prøver igen ..."
              sleep 30
            fi
          done

          if [ $tries -ge 20 ]; then
            echo "::warning ::Kunne ikke hente FT2019 efter flere forsøg. Fortsætter uden 2019."
          fi

      - name: Spejl FT 2015 (med retry/backoff)
        env:
          DIR: ${{ steps.cfg.outputs.DIR2015 }}
        run: |
          set -euo pipefail
          mkdir -p data/raw/ft/2015

          tries=0
          until [ $tries -ge 20 ]; do
            echo "== Spejler 2015 (forsøg $((tries+1))) =="
            if lftp -u "Valg","Valg" sftp://data.valg.dk -e "
              set net:timeout 20; set net:max-retries 1; set sftp:auto-confirm yes;
              mirror -c --verbose \"${DIR}/Valgresultater\" data/raw/ft/2015/Valgresultater;
              bye
            "; then
              echo "2015: OK"
              break
            else
              tries=$((tries+1))
              echo "2015: fejl – venter og prøver igen ..."
              sleep 30
            fi
          done

          if [ $tries -ge 20 ]; then
            echo "::warning ::Kunne ikke hente FT2015 efter flere forsøg. Fortsætter uden 2015."
          fi

      - name: Vis rå filer (overblik)
        run: |
          echo "== RAW 2019 ==" && find data/raw/ft/2019 -maxdepth 2 -type f | sort | head -n 40 || true
          echo "== RAW 2015 ==" && find data/raw/ft/2015 -maxdepth 2 -type f | sort | head -n 40 || true

      - name: Sæt op Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Byg CSV’er (JSON -> CSV i dit format)
        run: |
          if [ -d data/raw/ft/2015 ] || [ -d data/raw/ft/2019 ]; then
            node scripts/build-ft-csv.mjs
          else
            echo "::warning ::Ingen rådata tilgængelige – skipper byg."
          fi

      - name: Vis genererede CSV’er
        run: |
          echo "== CSV 2019 ==" && find data/ft/2019 -maxdepth 2 -type f -name "*.csv" | sort | head -n 40 || true
          echo "== CSV 2015 ==" && find data/ft/2015 -maxdepth 2 -type f -name "*.csv" | sort | head -n 40 || true

      - name: Commit & push ændringer
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(data): hent FT 2015/2019 fra valg.dk (robust) og byg CSV"
            git push
          else
            echo "Ingen ændringer at committe."
          fi
